version: '2.1'

services:
  ethToElk:
    image: mcpayment/ubuntu1404-java8:latest
    ports:
      - 9101:9101
    volumes:
      - /eth_to_elk:/var
      - /eth_to_elk/log:/var/log
    command: bash -c "java -Xms6g -Xms6g -jar /var/transport-0.0.1-SNAPSHOT.jar --spring.config.location=/var/application.properties"